CFLAGS=-Wall -g -std=c99 -o
CC=gcc

challenge_136_easy: challenge_136_easy.c
	$(CC) $(CFLAGS) $@ challenge_136_easy.c
	
challenge_136_easy_test: challenge_136_easy
	echo "Using Data"
	cat challenge_136_easy_test_data
	./challenge_136_easy < challenge_136_easy_test_data	

challenge_1_easy: challenge_1_easy.c
	$(CC) $(CFLAGS) $@ challenge_1_easy.c
	
challenge_3_easy: challenge_3_easy.c
	$(CC) $(CFLAGS) $@ challenge_3_easy.c
	
challenge_4_easy: challenge_4_easy.c
	$(CC) $(CFLAGS) $@ challenge_4_easy.c
	
challenge_5_easy: challenge_5_easy.c
	$(CC) $(CFLAGS) $@ challenge_5_easy.c
	
